### ISSUE TITLE
Landscape drag and drop errors item not found

### ISSUE THREAD

**Issue by nki2bpz** [DestinyItemManager/DIM#2409]
When in landscape it shows the item moved but gives the error item not found. I'm away from ps4 so I can't confirm whether its actually moving the item or it's a legit error. When using the store button on the item itself this doesn't error.

**Comment by duckmanBR** [comment]
I only get this error if I try to transfer only part of a stack, as stated on #2394 
Are you trying to transfer full stacks or items without stack (anything other than mods/consumables/shaders)?

**Comment by nki2bpz** [comment]
Standard weapon movement

-------- Original message --------

**Comment by bhollis** [comment]
I can't reproduce on iOS or desktop. Can anyone else?

**Comment by duckmanBR** [comment]
Couldn't reproduce on Android

**Comment by nki2bpz** [comment]
Just retested with newest version, same false error.

-------- Original message --------

**Comment by duckmanBR** [comment]
iOS/Android? Browser? (also, version of each)

**Comment by nki2bpz** [comment]
Chrome 62.0.3202.84
Android 7.0



-------- Original message --------

**Comment by nki2bpz** [comment]
To add some clarity, when moving items to vault, or from vault to character, this does not happen, only when moving from one character to the other. I thought since it only errored on a 2 part move maybe it was cuz my vault was 198/200 so I moved 20 weapons from vault to character without a single error. But as soon as I went back to character to character "bungie.net message the item requested was not found"

**Comment by duckmanBR** [comment]
I did only char x vault, sorry.
Error reproduced on Android 7.0 with Chrome Beta 63.0.3239.41 and Edge 1.0.0.1136

**Comment by duckmanBR** [comment]
Like I said in #2462, the error is also happening using the store option in the item popup, even in portrait.

**Comment by wmxp** [comment]
Having the same issue. Red box pops up: "Bungie.net message: The requested item was not found", despite correctly moving said item. Happens only when moving from character to character, not character to vault - all methods effected. (Loadout, drag and drop, click move to).   

Is causing problems with items not being moved when using large loadouts that shunt around a lot of gear. Especially has problems with applying the default equip slot for each loadout, which often fails now. Seems like the app is sending commands to Bungie's servers faster than it wants to process them.  

Tested on DIM 4.29.0 via Chrome on Windows 7, Chrome/Firefox on Android 7.1.2 and Chrome/Firefox on iOS 11.

**Comment by bhollis** [comment]
Can you all still reproduce this? I can't on iOS or Chrome desktop.

**Comment by bhollis** [comment]
Huh, I'm able to reproduce this, but *only* for Chrome on Android. Very weird.

**Comment by wmxp** [comment]
This issue has been fixed with release 4.30:  
https://github.com/DestinyItemManager/DIM/blob/master/docs/CHANGELOG.md#4300  

Everything is working fine now. If it's failing your on android device, you probably need to refresh to get the latest build.

**Comment by nki2bpz** [comment]
I have refreshed and tried the beta build, and updated chrome, still the same issue and I'm not the only one.

-------- Original message --------

**Comment by nki2bpz** [comment]
![screenshot_20171227-200556](https://user-images.githubusercontent.com/15946723/34397231-382718c6-eb42-11e7-9f98-e804426b7cff.png)
![screenshot_20171227-195618](https://user-images.githubusercontent.com/15946723/34397232-385d612e-eb42-11e7-93ac-c770963a6be7.png)

**Comment by nki2bpz** [comment]
It has gone back to only throwing the false error when moving char>char in landscape with drag and drop which us a huge improvement.

**Comment by bhollis** [comment]
I think we should try it again after the fix is merged.

**Comment by nki2bpz** [comment]
Lol, i thought it was, I got a message in email saying to try to refresh to latest version, so that was a response to the message but his msg didn't show up in thread.

**Comment by nki2bpz** [comment]
All good now
