### ISSUE TITLE
Exotic with active catalysts not tracking progress

### ISSUE THREAD

**Issue by jakibbe** [DestinyItemManager/DIM#2823]
For example, I have a Tractor Cannon that I've been upgrading -- I'm at least 28% of the way to meeting the kill requirement using this weapon. DIM shows 0% progress. Am I misunderstanding the progress that is being tracked, or should this value be incrementing?

Thanks!

![screenshot 2018-05-15 at 10 06 22 pm](https://user-images.githubusercontent.com/3777470/40092684-9f651e68-588c-11e8-8d3c-4a3d7e056554.png)
![screenshot 2018-05-15 at 10 04 45 pm](https://user-images.githubusercontent.com/3777470/40092685-9f80fd7c-588c-11e8-9e79-47174feef8ef.png)

**Comment by bhollis** [comment]
I have some fixes over in  #2825

**Comment by bhollis** [comment]
Take another look at beta and let me know what you think.

**Comment by jakibbe** [comment]
my tractor cannon MW is complete but at 0% and no checkboxes. you can see
that the kill tracker is working and it has MW magazine size perk

i just reloaded DIM and updated to Version 4.52.0.2083 (beta), built on
5/19/2018, 2:18:49 AM to be sure


​

**Comment by bhollis** [comment]
This has been fixed up as of last week. Let me know if you see any more weirdness.

**Comment by wickles** [comment]
Still happening for me. 

![2018-12-18 19_13_51-sharex-chrome](https://user-images.githubusercontent.com/4229542/50194741-666c5a00-02f9-11e9-8647-e95ba9206459.png)

**Comment by wickles** [comment]
@bhollis

**Comment by delphiactual** [comment]
@wickles go-to the `collections` page

**Comment by wickles** [comment]
I'm sorry, I misread this issue. I have items not tracking **Enemies Defeated** despite having it in-game, while others do show this value. Let me know if this is a known issue or if I should open another issue.
