### ISSUE TITLE
Selecting Powerful Friends class item perk in Loadout Optimizer shows no results

### ISSUE THREAD

**Issue by tehtrav** [DestinyItemManager/DIM#5080]
The problem seems to be isolated to the class item, it seems to work on the other armor pieces. 

![image](https://user-images.githubusercontent.com/351975/77928911-080d8580-7277-11ea-8f18-44d5b77a028d.png)

**Comment by ArkahnX** [comment]
Would like to add that it is not just the Powerful Friends mod, but I've also experienced this with Protective Light, and I imagine there are more mods out there that the loadout optimizer fails on.

Seems to be a weird bug. Here you can see my warlock shows as 0 options.
![protectivelight](https://user-images.githubusercontent.com/1167959/78690918-e5015800-78ac-11ea-96b8-6ac06e95f797.PNG)

Yet I have an armor piece with protective light equipped even!
![protectivelightwarlock](https://user-images.githubusercontent.com/1167959/78690986-f77b9180-78ac-11ea-87bf-f84ffe27e6ee.PNG)

Stranger still, if I look on my titan and hunter, it finds one valid class item
![protectivelighthunter](https://user-images.githubusercontent.com/1167959/78691296-4de8d000-78ad-11ea-87dd-a6939346532f.PNG)
![protectivelighttitan](https://user-images.githubusercontent.com/1167959/78691513-8c7e8a80-78ad-11ea-9ebd-ee83cea8656c.png)

however my titan has two valid class items as seen here
![protectivelighttitan2](https://user-images.githubusercontent.com/1167959/78691782-e1ba9c00-78ad-11ea-9568-19b86a9242da.PNG)

I don't have more time for investigation today, but I can try to take a deeper look into it tomorrow to see why this might be happening

**Comment by bhollis** [comment]
I think we had some bugs around damage type that should be fixed on beta now.

**Comment by ArkahnX** [comment]
I can follow up that as of `Version 6.4.0.6782 (beta), built on 4/7/2020, 9:12:31 AM` it is still an issue, I'll check again when I have time tomorrow to dig deeper.

**Comment by ArkahnX** [comment]
Digging into it a bit further, It looks like part of the issue is the changes to the seasonal mod slot. There is a different `plugSetHash` for each season, which wasn't a problem before. Now that Dawn mods can slot into worthy armor it looks like DIM is not accounting for these seasonal mods to be able to slot into different season's armor, this appears to be what is happening when you try to create a loadout that uses a season of dawn mod, but dont have season of dawn armor in the slot (even though undying and worthy will work in game)

Sorry for not referencing DIM code anywhere, I'm not able to build the master branch locally but I was able to validate my plugSetHash theory by breakpointing line 336 in utils https://github.com/DestinyItemManager/DIM/blob/810d494ad2793faac955fa9bb5bb65095d2a403d/src/app/loadout-builder/generated-sets/utils.ts#L336
For each of my characters, they were getting a different plugSetHash for Protective Light, I'm guessing based on whatever first piece of armor DIM could find that supported that mod.

Hopefully this helps!

**Comment by ryan-rushton** [comment]
I started work on a bit of a mods overhaul today so I will make sure this is fixed by the end of it all.
