### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'sort')

### ISSUE THREAD

**Issue by Scarcesss** [DestinyItemManager/DIM#8018]
### DIM Version

7.7.0

### Browser Details

Brave and chrome, same thing

### OS Details

Windows 10

### Describe the bug

Hi, since few months I'm facing this error message " Something went wrongTypeError Cannot read properties of undefined (reading 'sort') on titan my charracter when I try to reach the loadouts page, no pb for my warlock.
I'm using DIM v7.7.0 version.

Any suggestions?
Thanks in advance

### Logs

```shell
TypeError: Cannot read properties of undefined (reading 'sort')
at LoadoutView.tsx:95:73
at _arrayAggregator.js:17:32
at _createAggregator.js:19:12
at U (LoadoutView.tsx:95:22)
at aa (react-dom.production.min.js:157:137)
at $s (react-dom.production.min.js:267:460)
at Tu (react-dom.production.min.js:250:347)
at Ou (react-dom.production.min.js:250:278)
at ku (react-dom.production.min.js:250:138)
at mu (react-dom.production.min.js:243:163)
at react-dom.production.min.js:123:115
at scheduler.production.min.js:18:343
at $i (react-dom.production.min.js:122:325)
at Ki (react-dom.production.min.js:123:61)
at qi (react-dom.production.min.js:122:428)
at gu (react-dom.production.min.js:244:190)
at Object.notify (Subscription.js:15:7)
at Object.notifyNestedSubs (Subscription.js:85:15)
at i (Subscription.js:90:20)
at g (redux.js:296:32)
at index.js:20:16
at dispatch (redux.js:659:28)
at d2-stores.ts:233:9
```

**Comment by delphiactual** [comment]
Sentry issue: [DIM-17BA](https://sentry.io/organizations/destiny-item-manager/issues/2930699685/?referrer=github_plugin)

**Comment by Scarcesss** [comment]
I can't access the link... :/

**Comment by Scarcesss** [comment]
This is what I get after clinking on the link "Authentication error: You do not have access to the required GitHub organization.", please help @bhollis , @delphiactual , any sugestion ? I'm a beginer about all of this. Thanks in advance

**Comment by bhollis** [comment]
The link wasn't for you.

The latest beta should work now - let us know if it doesn't after updating.

**Comment by Scarcesss** [comment]
@bhollisn thanks for reply, ok, noticed, but unfortunately no, it still doesn't work.
Error code has changed with beta version v.7.71001403, it is now: "Cannot read properties of undefined (reading 'inPostmaster')"

**Comment by bhollis** [comment]
This should be fixed in the latest beta, let us know if it's not.
