### ISSUE TITLE
Sheets autofocus on iOS which hides the sheet

### ISSUE THREAD

**Issue by Aragornking41** [DestinyItemManager/DIM#8111]
### DIM Version

DIM (Destiny Item Manager) Version 7.8.0.1001470 (beta), built on 3/9/2022, 5:59:20 AM

### Browser Details

iOS mobile beta app

### OS Details

iOS 15.2.1

### Describe the bug

Some popup menus (such as subclass customize from the loadout edit menu or masterwork change on weapons menu) have the keyboard popup initially and don't display the menu until the keyboard is closed, it still shows the inventory. I have a couple of pics that display the issue but I know it's not easy to see the issue. If you have something you want me to do to show it better let me know.
![F817D7CD-4C9D-4788-87E2-FB9A31F94D9A](https://user-images.githubusercontent.com/63864737/157461010-40b628e5-4b51-4a67-914b-beb139a06a57.png)

**Comment by Aragornking41** [comment]
I just saw that the masterwork menu issue only happens when another menu is pulled up where the master work is opened from such as compare. If pulled up from the inventory it works properly but if opened from another popup menu, it opens the keyboard and hides both menus until the keyboard is closed. This corresponds to how the issue happens with subclass editing as well.

**Comment by bhollis** [comment]
Mostly fixed by #8082

**Comment by Aragornking41** [comment]
Hi, this is still happening in masterwork selection especially when opened from compare. Additionally the lack of scroll on search still cause options to not be visible. However the issue with the subclass customization is fixed. Just wanted to let you know in case you thought all of the issues were fixed.
